### ISSUE TITLE
Validate Access Permissions for repo 

### ISSUE THREAD

**Issue by sammykumar** [getcursor/docs#3]
Hey, I'm attempting to push my local branch `feat/add-react-admin` to this repo so that I can open PR for y'alls review.

I keep getting the following error while pushing:

```
sammykumar@Personal-MacBook-Pro docs % git push     
ERROR: Permission to getcursor/docs.git denied to sammykumar.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I'm thinking the repo's access permissions needs to be reviewed. Thanks!

**Comment by truell20** [comment]
I think maybe you need to make a fork that you do the PR from?

**Comment by sammykumar** [comment]
Ohhh my bad.
